{% set name = "aiopeewee" %}
{% set version = "0.4.2" %}
{% set sha256 = "be9c5f574dd353b1869fa61982840c753c50ffc0538b6a9f3625bb4990e46fa8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - pytest-runner
  run:
    - python>=3.6
    - peewee >=2.9.2
    - aiomysql >=0.0.9

test:
  imports:
    - aiopeewee

about:
  home: https://github.com/kszucs/aiopeewee
  summary: "Asyncio interface for Peewee ORM"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kszucs
