{% set version = "0.4.2" %}

package:
  name: aiopeewee
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/aiopeewee/aiopeewee-{{ version }}.tar.gz
  sha256: be9c5f574dd353b1869fa61982840c753c50ffc0538b6a9f3625bb4990e46fa8

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python <3
    - setuptools
    - pytest-runner
  run:
    - python <3
    - peewee >=2.9.2
    - aiomysql >=0.0.9

test:
  imports:
    - aiopeewee

about:
  home: https://github.com/kszucs/aiopeewee
  summary: "Asyncio interface for Peewee ORM"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kszucs
