travis:
  secure:
    BINSTAR_TOKEN: b9627gRf9GmpO62ovTJHatMBw8xD4houRU7U5t4Wwi4qUYFA0yr0iC5bZHCK1U+vGBLWPbx8I6JtRFQcu9FmvXxkADOTQKQHIdI0/V3jL7MmU1l5AorkLzCS9rJlUgOKCECXygBXqpmqOgl38U1hBpkUwBr/rsLmO/Ea468pfx+twGyL3GdLOP6y0cNLi8XdW5str2vf26Sez3Bg818tbkNyBdq1pose5drEXcCES2wYOKdCXnmL4KSZIMK4TERoA53Xn/9A8gYeAukje1YVFa4UWPFuoP5ly/r6Oe/VM+yFOMUnzAdU9e74jFCQg/9xbVN5bnfhGJUXfgf9o89dFaeSyu9J6t4S2iTUIvW3KPRXNyXzeCoQXzl7x87wX72Wc7rxB1yrPc5RIPVRI9QRIQeluUHS21Pfo/Fm37cRuSq2zhc6ivYLfEolgBwQGIQg9NoXwAGppJ2JRDUitR3m+qYT5pnom/7m2zTOLn2HxiW1iwvRfzpDagv9jRDT/5r1CVA0ibRIxhehhan/+BtSRHAQYKbxGnSNCSE+CWhrQMo5A2199FARKkXhBJKFeFVp1pg+EzPj6I0Bql9cdGfiLUHtGMoSo1OC/3DfOQ+R8ok4vtNJJUJjcHNqrl8odRuizjLLqKhgDCesfm41VhVjj1FR4FPRQ9CeZM7lTOAl8d8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
